resources:
  - url: http://127.0.0.1:5000/toggle-element.js
    type: module
views:
  - cards:
      - elements:
          - conditions:
              - entity: input_boolean.show_sun_icon
                state: 'on'
            elements:
              - entity: sun.sun
                style: 
                  left: 95%
                  top: 5%
                type: state-icon
            type: conditional
          - entities:
              - entity: input_boolean.show_sun_icon
                name: Show Sun
            style: 
              left: 90%
              top: 90%
            type: 'custom:toggle-entity-list-element.js'
        type: picture-elements       
image: 'https://upload.wikimedia.org/wikipedia/de/d/df/PH16-Floorplan_schematic.svg'
type: picture-elements
